### ISSUE TITLE
Consider infinite num_epochs

### ISSUE THREAD

**Issue by NickVeld** [lRomul/argus#10]
Currently the default num_epochs is 1 and there is no support for the  infinite num_epochs (using -1 for example).

https://github.com/lRomul/argus/blob/37c1cade3b82a9bffc289894458d80cf1720532d/argus/model/model.py#L169
https://github.com/lRomul/argus/blob/37c1cade3b82a9bffc289894458d80cf1720532d/argus/engine/engine.py#L227

What about this feature for the "I do not know how many epochs I need, I just want to provide the `EarlyStopping` callback or stop the training with `KeyboardInterrupt`".

Checking that either `num_epochs > 0` or `EarlyStopping_instance in callbacks` is a valid option.

**Comment by lRomul** [comment]
Interesting feature but I usually use any large number for this purpose.
You can also use infinity this way:
```python
model.fit(train_loader,
          val_loader=val_loader,
          num_epochs=float('inf'))
```

My goal is to keep the library as simple as possible, yet flexible enough. I don't think this is a necessary feature, but thanks for the idea!
