### ISSUE TITLE
Handle multi-GPU model

### ISSUE THREAD

**Issue by fpicetti** [lRomul/argus#5]
I am training a model on 4 different GPUs. During the training, I use the `MonitorCheckpoint` callback for saving the model on disk. Due to long training time, my script stops after training. The test is performed by hand, reinitializing a python kernel and loading the trained model. 

The loading is performed with `model = argus.load_model()` and, by printing the `model` variable, I can see the 4 devices I used in training. However, I would like to move the model to a single GPU for the tensor operations I need to perform must be on the same device. Indeed I got:
`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:2 and cuda:0!`

Is there any way to re-assign the cuda device? Using `model.set_device(0)` does not work, I can see all the previous GPU running.

Thanks in advance, and congratulations for the package!

**Comment by lRomul** [comment]
You can use `device` parameter of `argus.load_model`:

```python
params = {
    ...,
    'device': ['cuda:0', 'cuda:1', 'cuda:2', 'cuda:3']
}
model = CnnFinetune(params)
model.save(model_path)

# restarting

model = argus.load_model(model_path, device="cuda:0")

# other ways to handle devices 
model = argus.load_model(model_path, device=["cuda:0", "cuda:1"])
model.set_device("cuda:0") 
model.set_device(["cuda:2", "cuda:3"])

# by default device "cuda" is one gpu training on torch.cuda.current_device
model.set_device("cuda")  
```

I will make more complete documentation. Thank you for using the library!

**Comment by fpicetti** [comment]
Thanks, it worked!
